services:
  chat_app:
    container_name: "chat_app"
    build: ..
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    volumes:
      - ../app:/app
    networks:
      - backend_chat
    depends_on:
      - db

networks:
 backend_chat:
   driver: bridge
